# Generated by Django 4.2.2 on 2023-06-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaturtle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seaturtle',
            name='id',
        ),
        migrations.AlterField(
            model_name='seaturtle',
            name='date',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
