# Generated by Django 4.2.3 on 2023-07-13 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaturtle', '0002_remove_seaturtle_id_alter_seaturtle_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('problem', models.TextField()),
                ('explanation', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='seaturtle',
            name='correct_answer',
            field=models.TextField(null=True),
        ),
    ]
