# Generated by Django 4.2.3 on 2023-07-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaturtle', '0003_submitproblem_seaturtle_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='seaturtle',
            name='author',
            field=models.TextField(null=True),
        ),
    ]
