# Generated by Django 4.2.3 on 2023-07-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaturtle', '0004_seaturtle_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='seaturtle',
            name='main_charachter',
            field=models.TextField(null=True),
        ),
    ]
