# Generated by Django 4.2.3 on 2023-07-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaturtle', '0005_seaturtle_main_charachter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seaturtle',
            name='main_charachter',
        ),
        migrations.AddField(
            model_name='seaturtle',
            name='main_character',
            field=models.TextField(null=True),
        ),
    ]
