# Generated by Django 4.2.3 on 2023-07-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaturtle', '0006_remove_seaturtle_main_charachter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='alternative_word',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
