# Generated by Django 4.2.3 on 2023-07-22 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seaturtle', '0007_keyword_alternative_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.TextField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seaturtle.seaturtle')),
            ],
        ),
    ]
