# Generated by Django 4.2.3 on 2023-08-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaturtle', '0009_seaturtle_answer_plus'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLog',
            fields=[
                ('date', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
