# Generated by Django 4.2.3 on 2023-08-04 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seaturtle', '0010_questionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionLog',
        ),
    ]
