# Generated by Django 4.2.3 on 2023-08-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaturtle', '0011_delete_questionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.IntegerField(null=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
