# Generated by Django 4.2.4 on 2023-08-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaturtle', '0012_questionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlog',
            name='answer2',
            field=models.TextField(null=True),
        ),
    ]
