# Generated by Django 4.2.4 on 2023-08-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seaturtle', '0013_questionlog_answer2'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlog',
            name='question_kr',
            field=models.TextField(null=True),
        ),
    ]
